IF OBJECT_ID('tempdb.dbo.#Country', 'U') IS NOT NULL
  DROP TABLE #Country; 

CREATE TABLE #Country(
	[Code] [char](2) NOT NULL PRIMARY KEY,
	[ContinentCode] [char](2) NULL,
	[ContinentId] [int] NULL,
	[Name] [varchar](50) NOT NULL,
	[Iso3] [char](3) NOT NULL,
	[IsoNum] [int] NULL
)
GO

----------------------------
-- Records of countries
----------------------------
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AD', N'EU', N'Andorra', N'AND', 20)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AE', N'AS', N'United Arab Emirates', N'ARE', 784)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AF', N'AS', N'Afghanistan', N'AFG', 4)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AG', N'NA', N'Antigua and Barbuda', N'ATG', 28)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AI', N'NA', N'Anguilla', N'AIA', 660)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AL', N'EU', N'Albania', N'ALB', 8)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AM', N'AS', N'Armenia', N'ARM', 51)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AN', N'NA', N'Netherlands Antilles', N'ANT', 530)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AO', N'AF', N'Angola', N'AGO', 24)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AQ', N'AN', N'Antarctica', N'ATA', 10)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AR', N'SA', N'Argentina', N'ARG', 32)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AS', N'OC', N'American Samoa', N'ASM', 16)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AT', N'EU', N'Austria', N'AUT', 40)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AU', N'OC', N'Australia', N'AUS', 36)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AW', N'NA', N'Aruba', N'ABW', 533)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AX', N'EU', N'Åland', N'ALA', 248)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'AZ', N'AS', N'Azerbaijan', N'AZE', 31)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BA', N'EU', N'Bosnia and Herzegovina', N'BIH', 70)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BB', N'NA', N'Barbados', N'BRB', 52)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BD', N'AS', N'Bangladesh', N'BGD', 50)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BE', N'EU', N'Belgium', N'BEL', 56)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BF', N'AF', N'Burkina Faso', N'BFA', 854)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BG', N'EU', N'Bulgaria', N'BGR', 100)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BH', N'AS', N'Bahrain', N'BHR', 48)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BI', N'AF', N'Burundi', N'BDI', 108)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BJ', N'AF', N'Benin', N'BEN', 204)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BL', N'NA', N'Saint Barthélemy', N'BLM', 652)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BM', N'NA', N'Bermuda', N'BMU', 60)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BN', N'AS', N'Brunei Darussalam', N'BRN', 96)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BO', N'SA', N'Bolivia', N'BOL', 68)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BR', N'SA', N'Brazil', N'BRA', 76)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BS', N'NA', N'Bahamas', N'BHS', 44)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BT', N'AS', N'Bhutan', N'BTN', 64)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BV', N'AN', N'Bouvet Island', N'BVT', 74)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BW', N'AF', N'Botswana', N'BWA', 72)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BY', N'EU', N'Belarus', N'BLR', 112)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'BZ', N'NA', N'Belize', N'BLZ', 84)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CA', N'NA', N'Canada', N'CAN', 124)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CC', N'AS', N'Cocos (Keeling) Islands', N'CCK', 166)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CD', N'AF', N'Congo (Kinshasa)', N'COD', 180)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CF', N'AF', N'Central African Republic', N'CAF', 140)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CG', N'AF', N'Congo (Brazzaville)', N'COG', 178)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CH', N'EU', N'Switzerland', N'CHE', 756)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CI', N'AF', N'Côte d''Ivoire', N'CIV', 384)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CK', N'OC', N'Cook Islands', N'COK', 184)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CL', N'SA', N'Chile', N'CHL', 152)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CM', N'AF', N'Cameroon', N'CMR', 120)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CN', N'AS', N'China', N'CHN', 156)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CO', N'SA', N'Colombia', N'COL', 170)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CR', N'NA', N'Costa Rica', N'CRI', 188)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CU', N'NA', N'Cuba', N'CUB', 192)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CV', N'AF', N'Cape Verde', N'CPV', 132)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CX', N'AS', N'Christmas Island', N'CXR', 162)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CY', N'AS', N'Cyprus', N'CYP', 196)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'CZ', N'EU', N'Czech Republic', N'CZE', 203)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DE', N'EU', N'Germany', N'DEU', 276)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DJ', N'AF', N'Djibouti', N'DJI', 262)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DK', N'EU', N'Denmark', N'DNK', 208)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DM', N'NA', N'Dominica', N'DMA', 212)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DO', N'NA', N'Dominican Republic', N'DOM', 214)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'DZ', N'AF', N'Algeria', N'DZA', 12)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'EC', N'SA', N'Ecuador', N'ECU', 218)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'EE', N'EU', N'Estonia', N'EST', 233)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'EG', N'AF', N'Egypt', N'EGY', 818)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'EH', N'AF', N'Western Sahara', N'ESH', 732)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ER', N'AF', N'Eritrea', N'ERI', 232)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ES', N'EU', N'Spain', N'ESP', 724)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ET', N'AF', N'Ethiopia', N'ETH', 231)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FI', N'EU', N'Finland', N'FIN', 246)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FJ', N'OC', N'Fiji', N'FJI', 242)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FK', N'SA', N'Falkland Islands', N'FLK', 238)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FM', N'OC', N'Micronesia', N'FSM', 583)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FO', N'EU', N'Faroe Islands', N'FRO', 234)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'FR', N'EU', N'France', N'FRA', 250)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GA', N'AF', N'Gabon', N'GAB', 266)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GB', N'EU', N'United Kingdom', N'GBR', 826)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GD', N'NA', N'Grenada', N'GRD', 308)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GE', N'AS', N'Georgia', N'GEO', 268)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GF', N'SA', N'French Guiana', N'GUF', 254)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GG', N'EU', N'Guernsey', N'GGY', 831)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GH', N'AF', N'Ghana', N'GHA', 288)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GI', N'EU', N'Gibraltar', N'GIB', 292)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GL', N'NA', N'Greenland', N'GRL', 304)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GM', N'AF', N'Gambia', N'GMB', 270)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GN', N'AF', N'Guinea', N'GIN', 324)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GP', N'NA', N'Guadeloupe', N'GLP', 312)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GQ', N'AF', N'Equatorial Guinea', N'GNQ', 226)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GR', N'EU', N'Greece', N'GRC', 300)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GS', N'AN', N'South Georgia and South Sandwich Islands', N'SGS', 239)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GT', N'NA', N'Guatemala', N'GTM', 320)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GU', N'OC', N'Guam', N'GUM', 316)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GW', N'AF', N'Guinea-Bissau', N'GNB', 624)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'GY', N'SA', N'Guyana', N'GUY', 328)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HK', N'AS', N'Hong Kong', N'HKG', 344)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HM', N'AN', N'Heard and McDonald Islands', N'HMD', 334)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HN', N'NA', N'Honduras', N'HND', 340)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HR', N'EU', N'Croatia', N'HRV', 191)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HT', N'NA', N'Haiti', N'HTI', 332)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'HU', N'EU', N'Hungary', N'HUN', 348)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ID', N'AS', N'Indonesia', N'IDN', 360)
GO
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IE', N'EU', N'Ireland', N'IRL', 372)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IL', N'AS', N'Israel', N'ISR', 376)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IM', N'EU', N'Isle of Man', N'IMN', 833)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IN', N'AS', N'India', N'IND', 356)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IO', N'AS', N'British Indian Ocean Territory', N'IOT', 86)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IQ', N'AS', N'Iraq', N'IRQ', 368)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IR', N'AS', N'Iran', N'IRN', 364)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IS', N'EU', N'Iceland', N'ISL', 352)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'IT', N'EU', N'Italy', N'ITA', 380)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'JE', N'EU', N'Jersey', N'JEY', 832)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'JM', N'NA', N'Jamaica', N'JAM', 388)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'JO', N'AS', N'Jordan', N'JOR', 400)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'JP', N'AS', N'Japan', N'JPN', 392)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KE', N'AF', N'Kenya', N'KEN', 404)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KG', N'AS', N'Kyrgyzstan', N'KGZ', 417)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KH', N'AS', N'Cambodia', N'KHM', 116)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KI', N'OC', N'Kiribati', N'KIR', 296)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KM', N'AF', N'Comoros', N'COM', 174)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KN', N'NA', N'Saint Kitts and Nevis', N'KNA', 659)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KP', N'AS', N'Korea, North', N'PRK', 408)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KR', N'AS', N'Korea, South', N'KOR', 410)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KW', N'AS', N'Kuwait', N'KWT', 414)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KY', N'NA', N'Cayman Islands', N'CYM', 136)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'KZ', N'AS', N'Kazakhstan', N'KAZ', 398)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LA', N'AS', N'Laos', N'LAO', 418)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LB', N'AS', N'Lebanon', N'LBN', 422)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LC', N'NA', N'Saint Lucia', N'LCA', 662)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LI', N'EU', N'Liechtenstein', N'LIE', 438)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LK', N'AS', N'Sri Lanka', N'LKA', 144)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LR', N'AF', N'Liberia', N'LBR', 430)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LS', N'AF', N'Lesotho', N'LSO', 426)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LT', N'EU', N'Lithuania', N'LTU', 440)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LU', N'EU', N'Luxembourg', N'LUX', 442)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LV', N'EU', N'Latvia', N'LVA', 428)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'LY', N'AF', N'Libya', N'LBY', 434)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MA', N'AF', N'Morocco', N'MAR', 504)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MC', N'EU', N'Monaco', N'MCO', 492)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MD', N'EU', N'Moldova', N'MDA', 498)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ME', N'EU', N'Montenegro', N'MNE', 499)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MF', N'NA', N'Saint Martin (French part)', N'MAF', 663)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MG', N'AF', N'Madagascar', N'MDG', 450)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MH', N'OC', N'Marshall Islands', N'MHL', 584)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MK', N'EU', N'Macedonia', N'MKD', 807)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ML', N'AF', N'Mali', N'MLI', 466)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MM', N'AS', N'Myanmar', N'MMR', 104)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MN', N'AS', N'Mongolia', N'MNG', 496)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MO', N'AS', N'Macau', N'MAC', 446)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MP', N'OC', N'Northern Mariana Islands', N'MNP', 580)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MQ', N'NA', N'Martinique', N'MTQ', 474)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MR', N'AF', N'Mauritania', N'MRT', 478)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MS', N'NA', N'Montserrat', N'MSR', 500)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MT', N'EU', N'Malta', N'MLT', 470)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MU', N'AF', N'Mauritius', N'MUS', 480)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MV', N'AS', N'Maldives', N'MDV', 462)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MW', N'AF', N'Malawi', N'MWI', 454)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MX', N'NA', N'Mexico', N'MEX', 484)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MY', N'AS', N'Malaysia', N'MYS', 458)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'MZ', N'AF', N'Mozambique', N'MOZ', 508)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NA', N'AF', N'Namibia', N'NAM', 516)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NC', N'OC', N'New Caledonia', N'NCL', 540)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NE', N'AF', N'Niger', N'NER', 562)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NF', N'OC', N'Norfolk Island', N'NFK', 574)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NG', N'AF', N'Nigeria', N'NGA', 566)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NI', N'NA', N'Nicaragua', N'NIC', 558)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NL', N'EU', N'Netherlands', N'NLD', 528)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NO', N'EU', N'Norway', N'NOR', 578)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NP', N'AS', N'Nepal', N'NPL', 524)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NR', N'OC', N'Nauru', N'NRU', 520)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NU', N'OC', N'Niue', N'NIU', 570)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'NZ', N'OC', N'New Zealand', N'NZL', 554)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'OM', N'AS', N'Oman', N'OMN', 512)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PA', N'NA', N'Panama', N'PAN', 591)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PE', N'SA', N'Peru', N'PER', 604)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PF', N'OC', N'French Polynesia', N'PYF', 258)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PG', N'OC', N'Papua New Guinea', N'PNG', 598)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PH', N'AS', N'Philippines', N'PHL', 608)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PK', N'AS', N'Pakistan', N'PAK', 586)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PL', N'EU', N'Poland', N'POL', 616)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PM', N'NA', N'Saint Pierre and Miquelon', N'SPM', 666)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PN', N'OC', N'Pitcairn', N'PCN', 612)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PR', N'NA', N'Puerto Rico', N'PRI', 630)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PS', N'AS', N'Palestine', N'PSE', 275)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PT', N'EU', N'Portugal', N'PRT', 620)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PW', N'OC', N'Palau', N'PLW', 585)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'PY', N'SA', N'Paraguay', N'PRY', 600)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'QA', N'AS', N'Qatar', N'QAT', 634)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'RE', N'AF', N'Reunion', N'REU', 638)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'RO', N'EU', N'Romania', N'ROU', 642)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'RS', N'EU', N'Serbia', N'SRB', 688)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'RU', N'EU', N'Russian Federation', N'RUS', 643)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'RW', N'AF', N'Rwanda', N'RWA', 646)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SA', N'AS', N'Saudi Arabia', N'SAU', 682)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SB', N'OC', N'Solomon Islands', N'SLB', 90)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SC', N'AF', N'Seychelles', N'SYC', 690)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SD', N'AF', N'Sudan', N'SDN', 736)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SE', N'EU', N'Sweden', N'SWE', 752)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SG', N'AS', N'Singapore', N'SGP', 702)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SH', N'AF', N'Saint Helena', N'SHN', 654)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SI', N'EU', N'Slovenia', N'SVN', 705)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SJ', N'EU', N'Svalbard and Jan Mayen Islands', N'SJM', 744)
GO
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SK', N'EU', N'Slovakia', N'SVK', 703)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SL', N'AF', N'Sierra Leone', N'SLE', 694)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SM', N'EU', N'San Marino', N'SMR', 674)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SN', N'AF', N'Senegal', N'SEN', 686)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SO', N'AF', N'Somalia', N'SOM', 706)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SR', N'SA', N'Suriname', N'SUR', 740)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ST', N'AF', N'Sao Tome and Principe', N'STP', 678)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SV', N'NA', N'El Salvador', N'SLV', 222)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SY', N'AS', N'Syria', N'SYR', 760)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'SZ', N'AF', N'Swaziland', N'SWZ', 748)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TC', N'NA', N'Turks and Caicos Islands', N'TCA', 796)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TD', N'AF', N'Chad', N'TCD', 148)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TF', N'AN', N'French Southern Lands', N'ATF', 260)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TG', N'AF', N'Togo', N'TGO', 768)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TH', N'AS', N'Thailand', N'THA', 764)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TJ', N'AS', N'Tajikistan', N'TJK', 762)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TK', N'OC', N'Tokelau', N'TKL', 772)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TL', N'AS', N'Timor-Leste', N'TLS', 626)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TM', N'AS', N'Turkmenistan', N'TKM', 795)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TN', N'AF', N'Tunisia', N'TUN', 788)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TO', N'OC', N'Tonga', N'TON', 776)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TR', N'AS', N'Turkey', N'TUR', 792)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TT', N'NA', N'Trinidad and Tobago', N'TTO', 780)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TV', N'OC', N'Tuvalu', N'TUV', 798)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TW', N'AS', N'Taiwan', N'TWN', 158)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'TZ', N'AF', N'Tanzania', N'TZA', 834)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'UA', N'EU', N'Ukraine', N'UKR', 804)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'UG', N'AF', N'Uganda', N'UGA', 800)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'UM', N'OC', N'United States Minor Outlying Islands', N'UMI', 581)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'US', N'NA', N'United States of America', N'USA', 840)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'UY', N'SA', N'Uruguay', N'URY', 858)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'UZ', N'AS', N'Uzbekistan', N'UZB', 860)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VA', N'EU', N'Vatican City', N'VAT', 336)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VC', N'NA', N'Saint Vincent and the Grenadines', N'VCT', 670)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VE', N'SA', N'Venezuela', N'VEN', 862)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VG', N'NA', N'Virgin Islands, British', N'VGB', 92)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VI', N'NA', N'Virgin Islands, U.S.', N'VIR', 850)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VN', N'AS', N'Vietnam', N'VNM', 704)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'VU', N'OC', N'Vanuatu', N'VUT', 548)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'WF', N'OC', N'Wallis and Futuna Islands', N'WLF', 876)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'WS', N'OC', N'Samoa', N'WSM', 882)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'YE', N'AS', N'Yemen', N'YEM', 887)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'YT', N'AF', N'Mayotte', N'MYT', 175)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ZA', N'AF', N'South Africa', N'ZAF', 710)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ZM', N'AF', N'Zambia', N'ZMB', 894)
INSERT #Country ([Code], [ContinentCode], [Name], [Iso3], [IsoNum]) VALUES (N'ZW', N'AF', N'Zimbabwe', N'ZWE', 716)

Update #Country
Set ContinentId = (Select ContinentId from Continent Where ContinentCode = Code)

INSERT INTO Country (Name, Iso, Iso3, NumCode, ContinentId)
SELECT Name, Code, Iso3, IsoNum, ContinentId FROM #Country 